const Property = {
    image: './src/test/Mockdata/Screenshot_from_2019-07-08_13-30-34.png',
    property1: {
        price: 400,
        state: 'Kenya',
        city: 'Nairobi',
        type: 'apartment',
        address: 'kenya, 5th street',
    },
    property2: {
        price: '',
        state: 'Kenya',
        city: 'Nairobi',
        type: 'one bedroom',
        address: 'kenya, 5th street',
    },
    property3: {
        price: 400,
        state: '',
        city: 'Nairobi',
        type: 'one bedroom',
        address: 'kenya, 5th street',
    },
    property4: {
        price: 400,
        state: 'Kenya',
        city: '',
        type: 'one bedroom',
        address: 'kenya, 5th street',
    },
    property5: {
        price: 400,
        state: 'Kenya',
        city: 'Nairobi',
        type: '',
        address: 'kenya, 5th street',
    },
    property6: {
        price: 400,
        state: 'Kenya',
        city: 'Nairobi',
        type: 'one bedroom',
        address: '',
    },
    property7: {
        price: 't#',
        state: 'Kenya',
        city: 'Nairobi',
        type: 'one bedroom',
        address: '5th street down',
    },
    property8: {
        price: 400,
        state: 'K@',
        city: 'Nairobi',
        type: 'one bedroom',
        address: '5th street',
    },
    property9: {
        price: 400,
        state: 'Kenya',
        city: 'N@$',
        type: 'one bedroom',
        address: '5th street',
    },
    property10: {
        price: 400,
        state: 'Kenya',
        city: 'Nairobi',
        type: 'one%#%6',
        address: '5th street',
    },
    property11: {
        price: 400,
        state: 'Kenya',
        city: 'Nairobi',
        type: 'one bedroom',
        address: '5th&%$#',
    },
    property12: { price: 't#' },
    property13: {
        price: 400,
        state: 'Kenya',
        city: 'Nairobi',
        type: 'apartment',
        address: 'kenya, 5th street',
    },
    property14: { state: 'K@' },
    property15: { city: 'N@$' },
    property16: { type: 'one%#%6' },
    property17: { address: '5th&%$#' },
};

export default Property;
