const User = {
    user1: {
        firstname: 'bonbon',
        lastname: 'vic',
        email: 'bonbo@test.com',
        phoneNumber: '+254742087558',
        address: 'kenya',
        password: 'f5e4xhr43dh4t',
    },
    user2: {
        firstname: '',
        lastname: 'vic',
        email: 'bonbon@tes.com',
        phoneNumber: '+254742087558',
        address: 'kenya',
        password: 'ftdtfr5e4xh4t',
    },
    user3: {
        firstname: 'bonbon',
        lastname: '',
        email: 'bonbon@tes.com',
        phoneNumber: '+254742087558',
        address: 'kenya',
        password: 'ftdtfr5e4xhr4t',
    },
    user4: {
        firstname: 'bonbon',
        lastname: 'vic',
        email: '',
        phoneNumber: '+254742087558',
        address: 'kenya',
        password: 'ftdtfr5e4xhr44t',
    },
    user5: {
        firstname: 'bonbon',
        lastname: 'vic',
        email: 'bonbon@tst.com',
        phoneNumber: '+254742087558',
        address: '',
        password: 'ftdtfr5e4xhr4t',
    },
    user6: {
        firstname: 'bonbon',
        lastname: 'vic',
        email: 'bonbon@tst.com',
        phoneNumber: '',
        address: 'nairobi, kenya',
        password: 'ftdtfr5e4xhr4t',
    },
    user7: {
        firstname: 'bonbon',
        lastname: 'vic',
        email: 'bonbon@tst.com',
        phoneNumber: '45478',
        address: 'nairobi, kenya',
        password: 'ftdtfr5e4xhr4t',
    },
    user8: {
        firstname: 'bonbon',
        lastname: 'vic',
        email: 'bobon@test.com',
        phoneNumber: '+254742087558',
        address: 'kenya',
        password: '',
    },
    user9: {
        firstname: 'bonbon',
        lastname: 'vic',
        email: 'bonon@test.com',
        phoneNumber: '+254742087558',
        address: 'kenya',
        password: 'ftdr',
    },
    user10: {
        firstname: 'b&',
        lastname: 'vic',
        email: 'bonon@test.com',
        phoneNumber: '+254742087558',
        address: 'kenya',
        password: 'ftdr',
    },
    user11: {
        firstname: 'bonbon',
        lastname: 'v%',
        email: 'bonon@test.com',
        phoneNumber: '+254742087558',
        address: 'kenya',
        password: 'ftdr',
    },
    user12: {
        firstname: 'bonbon',
        lastname: 'vicker',
        email: 'bcom',
        phoneNumber: '+254742087558',
        address: 'kenya',
        password: 'ftdrgtytr5445',
    },
    user13: {
        firstname: 'bonbon',
        lastname: 'vic',
        email: 'bonbo@test.com',
        phoneNumber: '+254742087558',
        address: 'kenya',
        password: 'ftdtfr5e4x4t',
    },
    user14: {
        firstname: 'bonbon',
        lastname: 'vic',
        email: 'boybuny@test.com',
        phoneNumber: '+254742087558',
        address: 'kenya',
        password: 'f5e4xhr43dh4t',
    },
    user15: {
        firstname: 'bonbon',
        lastname: 'vic',
        email: 'boybunny@test.com',
        phoneNumber: '+254742087558',
        address: 'kenya',
        password: 'f5e4xhr43dh4t',
    },
    user16: {
        email: 'boybunny@test.com',
        password: 'f5e4xhr43dh4t',
    },
    user17: {
        email: '',
        password: 'ftdtfr5e4x4t',
    },
    user18: {
        email: '',
        password: '',
    },
    user19: {
        email: 'bonhdfsd@test.com',
        password: '',
    },
    user20: {
        email: 'bonhdfsd@test.com',
        password: 'ftdtfr5e4x4t',
    },
    user21: {
        email: 'boybunny@test.com',
        password: 'ftdtfr5u6g',
    },
};

export default User;
